subsitutions:
  _HOSTING_BUCKET: solarium.chronojam.co.uk

steps:
  - name: gcr.io/cloud-builders/bazel
    entrypoint: bash
    args: 
      - '-c'
      - |
        bazel build //site:solarium
        cp -r bazel-bin/site/solarium/* /site
    volumes:
      - name: "site"
        path: /site

  - name: gcr.io/cloud-builders/gsutil
    args: ["cp", "/site/*", "${_HOSTING_BUCKET}"]
    volumes:
      - name: "site"
        path: /site

timeout: 10m