sh_binary(
    name = "semver",
    srcs = ["semver.sh"],
    visibility = ["//visibility:public"],
)

sh_binary(
    name = "golang_version_stamper",
    srcs = ["golang_version_stamper.sh"],
    visibility = ["//visibility:public"],
)